[package]
name = "matext4cgmath"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
num-complex = "0.4.0"

[dev-dependencies]
rand = "0.8.5"
